[package]
name = "mp-chain-config"
authors.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true

[dependencies]

# Starknet
blockifier = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }

# Madara

mp-utils.workspace = true

# Other
anyhow = { workspace = true }
lazy_static = { workspace = true }
primitive-types.workspace = true
rstest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror.workspace = true
